name: Fetch Blog Test

on:
  # ワークフローを手動でトリガー
  workflow_dispatch:

jobs:
  test-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run test script
        run: python .github/scripts/fetch_blog.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update blog posts with test data"
          git push

# syntax
# https://docs.github.com/ja/actions/writing-workflows/workflow-syntax-for-github-actions

# workflows
# https://github.com/actions
